# Site settings
title: "sanjaykmenon.github.io"
description: > 
  Sanjay Krishna, Data Data
author: Sanjay Krishna
email: hi@sanjaykrishna.dev
twitter_username: sanjaykrishna
github_username: sanjaykmenon

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sanjaykmenon.github.io" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
